services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/code
    environment:
      MONGODB_URI: mongodb://admin:admin@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand({ping:1})'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
